version: "3"
services:
  node-app:
    container_name: react-node
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo-db
    image: mongo

    ports:
      - "27018:27017"
